### Your name:

<pre> Jimena Baripatti </pre>

### Collaborators:




In [1]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
import math
import operator 

Markdown referece can be found here:
    http://nestacms.com/docs/creating-content/markdown-cheat-sheet

Q1. Why would it be a problem if our training set and test set are the same.

<pre>  If we use the same data when we train and test our model, we will not have a way to evaluate how well our model works for new data. </pre>

Q2 [OPTIONAL]. Explain step by step the process to select k in the k-nearest neighbor algorithm (pseudocode) 

<pre> ENTER SOLUTION HERE </pre>

Q3. For the k-nearest regression. What happends when k = n. Where n is equal to the training size.

<pre>In the case of a categorical variable, the KNN algorithm assigns a new point to the class to which the majority of the k nearest points belong, so if k = training size the algorithm will always assign a new point to the label with the biggest proportion in the training set.  In the case of a quantitative variable, the algorithm will always estimate the same result which can be any form of average (mean, median, mode) of the dataset. </pre>

Q4. Define a function that takes a 1-d numpy array, a parameter k, and a number p.
The function returns an estimate equal to the mean of the closest k points to the number p

In [3]:
# calculate distance 
def get_distance(a, b):

    dist = pow((a - b), 2)
    return math.sqrt(dist)

In [4]:

"""Returns the k-neighbor estimate for p using data input_data.
    
    Keyword arguments:
    input_data -- numpy array of all the data
    k -- Number of k
    p -- input values
    
    If you make assumptions please explain them in the comments. i.e. tie breaking strategy.
    """
def k_neighbor(input_data, k, p):
    distances = []
    
    for x in range(len(input_data)): #calculate distance between p and all the instances
        
        dist = get_distance(p, input_data[x])
        
        distances.append((input_data[x], dist)) # create an array which contains each instances with its distance
        
    
    distances.sort(key=lambda tup: tup[1]) #sort list by distances
    
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][1])
    return np.mean(neighbors)

In [5]:
#Evaluate
data = np.array([1,3,4,5,7,8,11,12,13,15,19,24,25,29,40])
print(k_neighbor(input_data=data, k=3, p=5))
print(k_neighbor(input_data=data, k=2, p=15))
print(k_neighbor(input_data=data, k=3, p=25))
print(k_neighbor(input_data=data, k=1, p=55))
print(k_neighbor(input_data=data, k=3, p=55))
print(k_neighbor(input_data=data, k=10, p=55))

1.0
1.0
1.66666666667
15.0
23.6666666667
35.4


In [6]:
#Enter your observations and comments here


Q5. Similar to Q4 but for the n dimentional case. 

In [7]:
def l1_norm(a,b):
    """Returns the l1 norm (a,b)"""
    l1_norm = 0
    for x in range(len(a)):
        distance = abs(a[x] - b[x])
        l1_norm = l1_norm + distance
    return l1_norm

In [8]:
def l2_norm(a,b):
    """Returns the l2 norm (a,b)""" 
    l2_norm = 0
    for x in range(len(a)):
        l2_norm += pow((a[x] - b[x]), 2)
    return math.sqrt(l2_norm)

In [9]:

def k_neighbor_nd(input_data, k, p, metric='l1', mode='mean'):
    """Returns the k-neighbor estimate for p using data input_data.

    Keyword arguments:
    input_data -- numpy array of all the data
    k -- Number of k
    p -- input values
    metric -- l1 or l2. l1 norm or l2 norm https://en.wikipedia.org/wiki/Norm_(mathematics)
    mode -- estimator possible values = 'mean', 'median', 'max'
    
    Implement the l1 and l2 norms
    for mean, median and max, use np.mean, np.median and np.max
    """
    
    #YOUR CODE HERE
    size_data = len(input_data)
    
    #--------calculate distance----
    
    distances = [] #initiate list

    for x in range(len(input_data)):
        if metric == 'l1':     
            dist = l1_norm(p, input_data[x]) 
        elif metric == 'l2':
            dist = l2_norm(p, input_data[x])
    
        distances.append((input_data[x], dist)) # add the object (array, distance) to the list 
    
    distances.sort(key=operator.itemgetter(1)) #sort by distance, it is the second item in each (array, distance)
    
    #----calculate neighbors -----
    neighbors = []
    
    for x in range(k):
        neighbors.append(distances[x][0])
    
        
    neigh_array = np.array(neighbors) #transform list to array
    
    #-----calculate the k-neighbor ------
        
    if mode == 'mean':
        neighbor = neigh_array.mean(0)
       
        
    elif mode == 'median':
        neighbor = np.median(neigh_array, axis=0)
    
    elif mode == 'max':
        neighbor = neigh_array.max(0)
        
    return neighbor
    
  
   

In [10]:
data_4d = np.array([[4, 1, 2, 1], [1, 4, 2, 0], [3, 3, 1, 1], 
        [4, 0, 0, 0], [1, 2, 0, 0], [3, 4, 2, 3], 
        [2, 4, 4, 2], [2, 1, 4, 1], [3, 3, 2, 4], 
        [4, 3, 0, 4], [2, 2, 4, 0],[4, 3, 0, 2], 
        [4, 3, 0, 2], [0, 3, 4, 2]])

In [11]:
#Evaluate

print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 1, 4, 3], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=2, p=[4, 4, 0, 0], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 2, 2, 4], metric='l1', mode='max'))
print(k_neighbor_nd(input_data=data_4d, k=1, p=[2, 3, 3, 4], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 3, 3, 4], metric='l1', mode='median'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 1, 4, 3], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=2, p=[4, 4, 0, 0], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 2, 2, 4], metric='l2', mode='max'))
print(k_neighbor_nd(input_data=data_4d, k=1, p=[2, 3, 3, 4], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 3, 3, 4], metric='l2', mode='median'))

[ 2.          2.33333333  4.          1.        ]
[ 4.  3.  0.  2.]
[4 4 2 4]
[ 3.  3.  2.  4.]
[ 3.  4.  2.  3.]
[ 1.33333333  2.66666667  4.          1.66666667]
[ 3.5  3.   0.5  1.5]
[4 4 2 4]
[ 3.  3.  2.  4.]
[ 3.  4.  2.  3.]


In [12]:
#Enter your observations and comments here

Q6[Optional]. Read the documentation on KNeighborsRegressor

http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
    
Explore the source code:
    https://github.com/scikit-learn/scikit-learn/blob/ef5cb84a/sklearn/neighbors/regression.py
        
How different it is from your implementation? How well can you follow the code? Did you learn something new?

<pre> ENTER SOLUTION HERE </pre>